---
- name: Get account info from Azure
  hosts: localhost
  connection: local

  tasks:
    - name: Get facts for current logged in user
      delegate_to: localhost
      azure.azcollection.azure_rm_account_info:
